### ISSUE TITLE
Ordering Columns?

### ISSUE THREAD

**Issue by cdeterman** [kaneplusplus/bigmemory#23]
Right now we currently have `mpermute` which will reorder rows.  It seems to me we should have the option to reorder columns as well.  Thoughts?

**Comment by phaverty** [comment]
I like it.  I have a to-do item regarding deepcopy on my personal list. I'd
like to be able to copy arbitrary chunks of a bigmatrix to another
(possibly the same) bigmatrix. Perhaps operations could share some code?

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

On Wed, Sep 16, 2015 at 12:32 PM, Charles Determan <notifications@github.com

**Comment by cdeterman** [comment]
@phaverty, I believe my pull request will address the column reordering (once Mike accepts it or after we make a few more edits).  Did you have an example of these 'chunk' copies that you would like to do?  I'm not sure I understand what you are looking for?  Do you mean non-consecutive rows/columns?

**Comment by phaverty** [comment]
Hi Charles,

Sorry for the delay. I don't have a working example I can send, but I
sometimes have to merge a few bigmats into one. The operation is somewhat
like a do.call(cbind, ...) but sometimes the rows don't match up exactly.

bigmatA[ 1:10, 1:2 ] = bigmatB[ 2:11, 1:2 ]
bigmatA[ 1:10, 2:4 ] = bigmatB[ 1:10, 1:2 ]

It's not super fast, so I thought it might be nice to move this down to C.
It's a straightforward thing to do, so I'll eventually get around to it.  I
mostly mentioned it because it also would benefit from a API for modifying
one or two bigmatrices without bringing the data into R.


Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

On Fri, Sep 18, 2015 at 12:19 PM, Charles Determan <notifications@github.com

**Comment by kaneplusplus** [comment]
The pull request has been merged. Thanks.
